runtime: nodejs
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2.0
  disk_size_gb: 10

env_variables:
  REACT_APP_ENV: 'production'

beta_settings:
  cloud_sql_instances: core-voto-ucv:us-central1:voto-ucv